### ISSUE TITLE
Weird Errors when trying to use async reader with threading

### ISSUE THREAD

**Issue by tomzhu6066** [nsqio/pynsq#181]
I have a spider application which has to use 300+ concurrent consumers. I have no choice but to use async way of reader by following "Asynchronous example" from [docs](https://pynsq.readthedocs.io/en/latest/reader.html).
My code is as follows:
I use a `cleanup_loop` to check if thread is dead and make the message `finish()`
```
consume_tasks = []

def consume_func(content):
    # do custom stuff with content
    time.sleep(5)
    return

def async_handler(message):
    global consume_tasks
    message.enable_async()

    job = threading.Thread(
        target=consume_func,
        args=(message.body.decode(),)
    )
    consume_tasks.append({
        'message': message,
        'job': job,
    })
    job.start()

def cleanup_loop():
    global consume_tasks
    while True:
        unfinished_tasks = []
        for task in consume_tasks:
            if not task.get('job').is_alive():
                task.get('message').finish()
            else:
                unfinished_tasks.append(task)
        consume_tasks = unfinished_tasks
        time.sleep(0.1)

reader = nsq.Reader(message_handler=handler, lookupd_http_addresses='',
                    topic='Test123', channel='async', max_in_flight=10)
threading.Thread(target=cleanup_loop).start()
nsq.run()

```
I test with 20 concurrent producers pushing to this reader and it sometimes works (50%). Sometime is throwing me weird errors:
```
Traceback (most recent call last):
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized

Traceback (most recent call last):
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError

```
and then
```
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d08fd9d001' (Stream is closed)
```
From full day of debugging, I know this error is coming from the line `task.get('message').finish()` but I don't know why.

Can anyone help me with this? Any advice is welcome!
If this is not going good with Threading, what should I use instead?

**Comment by jehiah** [comment]
@tomzhu6066 can you provide a larger section of client logs, and the matching logs from the nsqd side? That might help better identify what is causing the disconnection.

**Comment by ploxiln** [comment]
```
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized
```

This is most likely because you're using a tornado IOLoop from multiple threads. See conversation around https://github.com/tornadoweb/tornado/pull/2008#issuecomment-297975575

**Comment by tomzhu6066** [comment]
@jehiah 
Here's nsqd stderr:
```
[nsqd] 2017/06/06 10:42:08.971153 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2017/06/06 10:42:23.967952 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2017/06/06 10:42:26.826300 TCP: new client(127.0.0.1:61443)
[nsqd] 2017/06/06 10:42:26.826615 CLIENT(127.0.0.1:61443): desired protocol magic '  V2'
[nsqd] 2017/06/06 10:42:26.827184 [127.0.0.1:61443] IDENTIFY: {ShortID:zhuyuhaodeMacBook-Pro LongID:zhuyuhaodeMacBook-Pro.local ClientID:zhuyuhaodeMacBook-Pro Hostname:zhuyuhaodeMacBook-Pro.local HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:false DeflateLevel:6 Snappy:false SampleRate:0 UserAgent:pynsq/0.8.0 MsgTimeout:0}
[nsqd] 2017/06/06 10:42:32.842495 ERROR: [127.0.0.1:61443] - E_FIN_FAILED FIN 0c18c9d21fd9d000 failed ID not in flight - ID not in flight
[nsqd] 2017/06/06 10:42:32.842927 PROTOCOL(V2): [127.0.0.1:61443] exiting ioloop
[nsqd] 2017/06/06 10:42:32.843004 ERROR: client(127.0.0.1:61443) - failed to read command - read tcp 127.0.0.1:4150->127.0.0.1:61443: read: connection reset by peer
[nsqd] 2017/06/06 10:42:32.843087 PROTOCOL(V2): [127.0.0.1:61443] exiting messagePump
```
while my application throwing me:
```
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d21fd9d000' (Existing exports of data: object cannot be re-sized)
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/tornado/iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d220d9d000' (Stream is closed)
consuming new message: hahahaha1
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d22219d000' (Stream is closed)
WARNING:nsq.reader:[127.0.0.1:4150:athena.Test123:async] connection closed
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d22399d000' (Stream is closed)
consuming new message: hahahaha1
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: ConnectionClosedError('Stream is closed',)

```

**Comment by tomzhu6066** [comment]
I cleaned my code by removing `cleanup_loop` and let thread itself calls `message.finish()`:
```
def consume_func(content):
    # do custom stuff with content
    return

def consume_func_with_finish(message):
    consume_func(message.body.decode())
    message.finish()

def async_handler(message):
    message.enable_async()

    job = threading.Thread(
        target=consume_func,
        args=(message,)
    )
    job.start()

reader = nsq.Reader(message_handler=consume_func_with_finish, lookupd_http_addresses='',
                    topic='TestTopic', channel='async', max_in_flight=10)
nsq.run()
```
And I got error still on second 5 messages. But it's different this time:
```
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d33ad9d000' (can't convert negative int to unsigned)
WARNING:nsq.reader:[127.0.0.1:4150:athena.Test123:async] connection closed
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d33c59d000' (Existing exports of data: object cannot be re-sized)
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d33d19d000' (Stream is closed)
ERROR:nsq.client:[127.0.0.1:4150:athena.Test123:async] ERROR: SendError: failed to send FIN b'0c18c9d33d99d000' (Stream is closed)
```
And I noticed if I delete topic everytime before I run the test, it's always working.

**Comment by tomzhu6066** [comment]
Finally, I changed my mind from using `message.finish()` after death of thread to:
- When getting new task, immediately calls `message.finish()` and put task into memory
- Use independent threads cleaning tasks from memory, to get away from pynsq life circle (tournado ioloop).
- Set limitation on memory pool (same amount as `max_in_flight`) avoiding tasks comming like waterfall

Here's the code and it's working fine for now:
```
message_pool = []
lock = threading.Lock()

def consume_func(content):
    # do custom stuff with content
    time.sleep(5)
    return

def thread_consumer():
    while True:
        message_body = None

        lock.acquire()
        global message_pool
        if message_pool:
            message_body = message_pool.pop()
        lock.release()

        if message_body:
            try:
                consume_func(message_body)
            except Exception as e:
                logger.error('异步消费时出错:')
                logger.exception(e)
        else:
            time.sleep(0.1)

def async_handler(message):
    global message_pool
    message.enable_async()

    while True:
        if len(message_pool) < max_threads_in_worker:
            lock.acquire()
            message_pool.append(message.body.decode())
            lock.release()
            message.finish()
            break
        else:
            time.sleep(0.1)

for i in range(max_threads_in_worker):
    job = threading.Thread(target=thread_consumer)
    job.start()

r, nsq = get_nsq_reader(async_handler, 'athena.'+self.listen_queue, 'async', max_threads_in_worker)
nsq.run()
```

**Comment by ploxiln** [comment]
Looks like you found a resolution to your issue.

(Though you mark messages finished before consume_func() really finishes with them, which is less than ideal.)

**Comment by nmante** [comment]
Can the message itself be added to the message_pool (not just the body)? And then `message.finish()` be called from the `consume_func`?

**Comment by ploxiln** [comment]
The problem (in this case) is you can't get a message on one thread, and `finish()` it on a different thread.

However, you could probably use a [ThreadPoolExecutor](https://docs.python.org/3.5/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) to run the work on another thread, and when the work is finished, then calling `message.finish()` in the original event-loop thread.

**Comment by vision9527** [comment]
```
import traceback
import threading
import nsq
import time, json

def message_handler(message):
    try:
        # _ = func(json.loads(message.body))
        data = json.loads(message.body)
        print("start_data:" + str(data))
        time.sleep(int(data))
        print("end_data:" + str(data))
    except Exception as e:
        print(e)
    finally:
        message.finish()
    return True

def handler(message):
    message.enable_async()
    thread = threading.Thread(target=message_handler, args=(message, ))
    thread.start()
    return True

reader = nsq.Reader(message_handler=handler, nsqd_tcp_addresses='127.0.0.1:4150',
                        topic='test_topic', channel='test_topic', max_in_flight=1)
nsq.run()
```

**Comment by ploxiln** [comment]
It is not correct to call `message.finish()` from another thread because that will end up running callbacks which interact with the event loop from the other thread. It may work most of the time, but on rare occasions it will cause strange exceptions.

If you use tornado-5.x you can use [IOLoop.run_in_executor](https://www.tornadoweb.org/en/branch5.1/ioloop.html#tornado.ioloop.IOLoop.run_in_executor) to run the bulk of the message processing in a separate thread, and get an awaitable/yieldable future, so you can call `message.finish()` in the original IOLoop thread after it finishes.

**Comment by vision9527** [comment]
> The problem (in this case) is you can't get a message on one thread, and `finish()` it on a different thread.
> 
> However, you could probably use a [ThreadPoolExecutor](https://docs.python.org/3.5/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) to run the work on another thread, and when the work is finished, then calling `message.finish()` in the original event-loop thread.

How to call message.finish() in original event-loop thread?I have poor experience in concurrent programming. Can you provide some code demo? Please

**Comment by ploxiln** [comment]
```python
def process_thread(msg_body):
    # do stuff with msg body
    time.sleep(5)

def handler(message):
    message.enable_async()

    def finish():
        message.finish()

    loop = tornado.ioloop.IOLoop.current()
    fut = loop.run_in_executor(None, process_thread, message.body)
    loop.add_future(fut, finish)
```

**Comment by vision9527** [comment]
> ```python
> def process_thread(msg_body):
>     # do stuff with msg body
>     time.sleep(5)
> 
> def handler(message):
>     message.enable_async()
> 
>     def finish():
>         message.finish()
> 
>     loop = tornado.ioloop.IOLoop.current()
>     fut = loop.run_in_executor(None, process_thread, message.body)
>     loop.add_future(fut, finish)
> ```

but... my tornado is 4.5.3 , no run_in_executor method.

**Comment by lambdaq** [comment]
getting the same error with pynsq==0.9.0
