### ISSUE TITLE
can pynsq pub str type in python3?

### ISSUE THREAD

**Issue by qhgongzi** [nsqio/pynsq#187]
```python
import nsq
import tornado.ioloop
import time

def pub_message():
    writer.pub('test', time.strftime('%H:%M:%S'), finish_pub)

def finish_pub(conn, data):
    print(data)

writer = nsq.Writer(['127.0.0.1:4150'])
tornado.ioloop.PeriodicCallback(pub_message, 1000).start()
nsq.run()
```

this demo of writer in document can't work in python3 because it will throw a error:

```
SendError: send error (None)
ERROR:nsq.writer:[xxxxserver:4150] failed to send pub

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pynsq-0.8.1-py3.5.egg/nsq/writer.py", line 149, in _pub
    conn.send(cmd(*args))
  File "/usr/local/lib/python3.5/site-packages/pynsq-0.8.1-py3.5.egg/nsq/protocol.py", line 123, in pub
    return _command(PUB, data, topic)
  File "/usr/local/lib/python3.5/site-packages/pynsq-0.8.1-py3.5.egg/nsq/protocol.py", line 76, in _command
    assert isinstance(body, bytes_types), 'body must be a bytestring'
AssertionError: body must be a bytestring
```

but when change the pub code to:
```python
writer.pub('test1', time.strftime('%H:%M:%S').encode(), finish_pub)
```
it will works fine(converted str to bytes manually).

can pynsq remove this assert because the str will be convert to bytes in next line.
```python
def _command(cmd, body, *params):
    body_data = b''
    params_data = b''
    if body:
        assert isinstance(body, bytes_types), 'body must be a bytestring'
        body_bytes = to_bytes(body)  # raises if not convertible to bytes
        body_data = struct_l.pack(len(body)) + body_bytes
    if len(params):
        params = [to_bytes(p) for p in params]
        params_data = b' ' + b' '.join(params)
    return b''.join((cmd, params_data, NL, body_data))
```
or document that: only bytes msg is allowed?

**Comment by mreiferson** [comment]
This is intentional, we chose not to auto-convert to bytes inside the library and force the user to properly encode.

Thanks for your question, gonna close.
