### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cevin** [nsqio/pynsq#222]
```
>>> import nsq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/a/venv/lib/python3.7/site-packages/nsq/__init__.py", line 29
    from .async import AsyncConn
              ^
SyntaxError: invalid syntax
```

python 3.7.x

**Comment by ploxiln** [comment]
fixed in #212 (but there have been no tagged releases since then)
