### ISSUE TITLE
just demo code add tls option, show me error, but can receive message

### ISSUE THREAD

**Issue by HaoweiCh** [nsqio/pynsq#237]
```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x10651e0d0>)
Traceback (most recent call last):
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/iostream.py", line 575, in wrapper
    self._maybe_add_error_listener()
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/iostream.py", line 941, in _maybe_add_error_listener
    self._add_io_state(ioloop.IOLoop.READ)
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/iostream.py", line 974, in _add_io_state
    self.io_loop.update_handler(self.fileno(), self._state)
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/ioloop.py", line 732, in update_handler
    self._impl.modify(fd, events | self.ERROR)
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/platform/kqueue.py", line 45, in modify
    self.unregister(fd)
  File "/Users/c/.pyenv/versions/script/lib/python3.7/site-packages/tornado/platform/kqueue.py", line 49, in unregister
    events = self._active.pop(fd)
KeyError: -1
```

pynsq==0.8.3
tornado==4.5.3

certifi==2018.8.24
python-snappy

run code here
```
def handler(message):
    print(message)
    return True


# :param tls_options: dictionary of options to pass to `ssl.wrap_socket()
#         <http://docs.python.org/2/library/ssl.html#ssl.wrap_socket>`_ as
#         ``**kwargs``
r = nsq.Reader(
    message_handler=handler,
    snappy=True,
    tls_v1=True,
    tls_options={
        'cert_reqs': ssl.CERT_NONE,
        # 'ssl_version': ssl.PROTOCOL_TLSv1,
        'certfile': '/tmp/nsqtmp/client.pem',
        'keyfile': '/tmp/nsqtmp/client.key',
        # 'ca_certs': '/tmp/nsqtmp/CAroot.pem',
    },
    nsqd_tcp_addresses=['127.0.0.1:4150'],
    topic='test', channel='default')
nsq.run()
```

**Comment by custa** [comment]
`import logging
import ssl
import time
import nsq
import os

logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)


def handler(message):
    time.sleep(1)
    logging.info(message.body)
    return True


if __name__ == "__main__":
    dirpath = os.getcwd()
    print("current directory is : " + dirpath)
    opts = {
        'cert_reqs': ssl.CERT_REQUIRED,
        'keyfile': './client-key.pem',
        'certfile': './client-cert.pem',
        'ca_certs': './ca.pem'
    }
    r = nsq.Reader(
        message_handler=handler,
        nsqd_tcp_addresses=['SZX1000501923:14150'],
        topic='topic',
        channel='channel',
        tls_v1=True,
        tls_options=opts)
    nsq.run()
`

2019-07-31 18:00:04,050 [topic:channel] starting reader for topic/channel...
2019-07-31 18:00:04,050 [SZX1000501923:14150:topic:channel] connecting to nsqd
2019-07-31 18:00:04,061 [SZX1000501923:14150:topic:channel] IDENTIFY sent {'short_id': 'C00188189A', 'long_id': 'C00188189A', 'client_id': 'C00188189A', 'hostname': 'C00188189A', 'heartbeat_interval': 30000, 'feature_negotiation': True, 'tls_v1': True, 'snappy': False, 'deflate': False, 'deflate_level': 6, 'output_buffer_timeout': 250, 'output_buffer_size': 16384, 'sample_rate': 0, 'user_agent': 'pynsq/0.8.3'}
2019-07-31 18:00:04,066 [SZX1000501923:14150:topic:channel] IDENTIFY received {'max_rdy_count': 2500, 'version': '1.1.0', 'max_msg_timeout': 900000, 'msg_timeout': 60000, 'tls_v1': True, 'deflate': False, 'deflate_level': 6, 'max_deflate_level': 6, 'snappy': False, 'sample_rate': 0, 'auth_required': False, 'output_buffer_size': 16384, 'output_buffer_timeout': 250}
Traceback (most recent call last):
  File "D:/Code/nsq-py-example/reader/pynsq/main.py", line 32, in <module>
    nsq.run()
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\nsq\__init__.py", line 48, in run
    tornado.ioloop.IOLoop.instance().start()
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\tornado\ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\tornado\platform\select.py", line 63, in poll
    self.read_fds, self.write_fds, self.error_fds, timeout)
ValueError: file descriptor cannot be a negative integer (-1)

**Comment by custa** [comment]
```
import logging
import ssl
import time
import nsq

logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)


def handler(message):
    time.sleep(1)
    logging.info(message.body)
    return True


if __name__ == "__main__":
    opts = {
        'cert_reqs': ssl.CERT_REQUIRED,
        'keyfile': './client-key.pem',
        'certfile': './client-cert.pem',
        'ca_certs': './ca.pem'
    }
    r = nsq.Reader(
        message_handler=handler,
        nsqd_tcp_addresses=['SZX1000501923:14150'],
        topic='topic',
        channel='channel',
        tls_v1=True,
        tls_options=opts)
    nsq.run()
```


2019-07-31 18:00:04,050 [topic:channel] starting reader for topic/channel...
2019-07-31 18:00:04,050 [SZX1000501923:14150:topic:channel] connecting to nsqd
2019-07-31 18:00:04,061 [SZX1000501923:14150:topic:channel] IDENTIFY sent {'short_id': 'C00188189A', 'long_id': 'C00188189A', 'client_id': 'C00188189A', 'hostname': 'C00188189A', 'heartbeat_interval': 30000, 'feature_negotiation': True, 'tls_v1': True, 'snappy': False, 'deflate': False, 'deflate_level': 6, 'output_buffer_timeout': 250, 'output_buffer_size': 16384, 'sample_rate': 0, 'user_agent': 'pynsq/0.8.3'}
2019-07-31 18:00:04,066 [SZX1000501923:14150:topic:channel] IDENTIFY received {'max_rdy_count': 2500, 'version': '1.1.0', 'max_msg_timeout': 900000, 'msg_timeout': 60000, 'tls_v1': True, 'deflate': False, 'deflate_level': 6, 'max_deflate_level': 6, 'snappy': False, 'sample_rate': 0, 'auth_required': False, 'output_buffer_size': 16384, 'output_buffer_timeout': 250}
Traceback (most recent call last):
  File "D:/Code/nsq-py-example/reader/pynsq/main.py", line 32, in <module>
    nsq.run()
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\nsq\__init__.py", line 48, in run
    tornado.ioloop.IOLoop.instance().start()
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\tornado\ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "D:\Anaconda3\envs\pynsq\lib\site-packages\tornado\platform\select.py", line 63, in poll
    self.read_fds, self.write_fds, self.error_fds, timeout)
ValueError: file descriptor cannot be a negative integer (-1)
