### ISSUE TITLE
Reader - Example in docs doesn't work

### ISSUE THREAD

**Issue by flynnplatt** [nsqio/pynsq#268]
I'm trying to create a simple reader/writer using Docker and while the writer seems to work, the reader continually fails with a `Connection Closed` error.

Here's the code:
```
import os
import logging

import nsq

logging.basicConfig(level=logging.NOTSET)

nsq_http_url = os.environ.get("NSQ_HTTP_ENDPOINT")

buf = []

def process_message(message):
    global buf
    message.touch()
    message.enable_async()
    # cache the message for later processing
    buf.append(message)
    if len(buf) >= 3:
        for msg in buf:
            print(msg, flush=True)
            msg.finish()
        buf = []
    else:
        print("deferring processing", flush=True)


def start_queue_readers(message_callback):
    global nsq_http_url

    _ = nsq.Reader(
        message_handler=process_message,
        lookupd_http_addresses=[nsq_http_url],
        topic="nsq-test",
        channel="00",
        max_in_flight=9,
    )
    nsq.run()
```

When I run I get the following output:
```
 INFO:nsq.reader:[5aa66c9417c5:4150:nsq-test:00] connecting to nsqd
 WARNING:nsq.reader:[5aa66c9417c5:4150:nsq-test:00] connection closed
 ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xffff78573d30>, <Future finished exception=StreamClosedError('Stream is closed')>)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/tornado/ioloop.py", line 758, in _run_callback
     ret = callback()
   File "/usr/local/lib/python3.9/site-packages/tornado/stack_context.py", line 300, in null_wrapper
     return fn(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/nsq/conn.py", line 242, in _connect_callback
     fut.result()
 tornado.iostream.StreamClosedError: Stream is closed
```

The method `start_queue_readers` is being called from the `main` function in another module that will eventually provide a callback function to do more than just print the contents of messages.

I've tried various alterations but they all seem to result in the same error. This current should be almost identical to the example code provided here: https://pynsq.readthedocs.io/en/latest/reader.html unless I'm missing something quite obvious.

Thanks for any help.

**Comment by flynnplatt** [comment]
The issue seems to have been with a Docker networking gotcha. Adding `--broadcast-address=127.0.0.1` to the `nsqd` container and ensuring that the host ports mapped to the same container ports fixed the issue.
